// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBqgb7BTo6W1WYoZups88EDrD4Q7ird5E',
    appId: '1:797520807518:web:a07af8f9a03dff22d296cf',
    messagingSenderId: '797520807518',
    projectId: 'surveyapp-34a4f',
    authDomain: 'surveyapp-34a4f.firebaseapp.com',
    storageBucket: 'surveyapp-34a4f.appspot.com',
    measurementId: 'G-C4QK1F8QX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBnUffl8yuGKGGGk9rsB8W5T9c-oENRpI',
    appId: '1:797520807518:android:1012cfe96d49ab7ad296cf',
    messagingSenderId: '797520807518',
    projectId: 'surveyapp-34a4f',
    storageBucket: 'surveyapp-34a4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQDvCNqDM3Z05dxoesAoCji19I4wx6bY',
    appId: '1:797520807518:ios:05ab2b225bcd2fb3d296cf',
    messagingSenderId: '797520807518',
    projectId: 'surveyapp-34a4f',
    storageBucket: 'surveyapp-34a4f.appspot.com',
    iosClientId: '797520807518-qc75ohke4htg0ui8i6i8p217v8f93h65.apps.googleusercontent.com',
    iosBundleId: 'com.mizwar.surveyAppUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmQDvCNqDM3Z05dxoesAoCji19I4wx6bY',
    appId: '1:797520807518:ios:068138eb4118b651d296cf',
    messagingSenderId: '797520807518',
    projectId: 'surveyapp-34a4f',
    storageBucket: 'surveyapp-34a4f.appspot.com',
    iosClientId: '797520807518-bl2m2ap7anlpchnen69bvraapspvh65n.apps.googleusercontent.com',
    iosBundleId: 'com.mizwar.surveyAppUser.RunnerTests',
  );
}
